spring.application.name=gymlife
server.port=8080

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/gymlife
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# MySQL
# spring.datasource.url=jdbc:mysql://localhost:3306/gym?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
# spring.datasource.username=root
# spring.datasource.password=admin
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jackson.serialization.fail-on-empty-beans=false

# URL Base para la App y Códigos QR (Torniquete y Correos)
gymlife.app.base-url=http://192.168.100.39:8080

# Tiempo de enfriamiento Anti-Passback para torniquete en minutos
gymlife.turnstile.cooldown-minutes=15

# Configuración de Servidor de Correo Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ing.dazaeev@gmail.com
spring.mail.password=yqzh thoz joab nhtt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

